### ISSUE TITLE
Add `ddev-get` as topic label to the repo details

### ISSUE THREAD

**Issue by rpkoller** [TravisCarden/ddev-drupal-xb-dev#18]
would you consider adding `ddev-get` as a topic to the repository details? That way your addon could be found when a user is entering `ddev addon list --all`

**Comment by TravisCarden** [comment]
Sure, @rpkoller. I didn't do so in the first place because I assumed this project was too niche, but since you and @rfay don't think so... It's done. Thanks. 🙂
