### ISSUE TITLE
Patch Drupal core for SQLite field type mapping to support JSON fields

### ISSUE THREAD

**Issue by mglaman** [TravisCarden/ddev-drupal-xb-dev#22]
We uncovered that Drupal throws a fatal error when introspecting schema in SQLite and a column uses JSON. See https://www.drupal.org/project/drupal/issues/3487533

This doesn't error when first inserting a table since it trusts the value of `sqlite_type`. But when updating a table or trying to remove a table, Drupal will die since it doesn't know how to handle the JSON column. This is specific to SQLite since it tries to manually take a column's schema and use its field mapping.

We discovered it before XB did in our usage. Now it's causing a proposed MR to fail: https://git.drupalcode.org/project/experience_builder/-/merge_requests/417#note_412858

I'm going to document it in the XB `CONTRIBUTING.md` about the patch. But it'd be worth having this addon apply the patch as well, since XB is using JSON.

**Comment by TravisCarden** [comment]
Thanks, @mglaman. I saw in Slack that you're going to investigate a different approach first. Let me know if you come to the conclusion that we still need to pursue this here.

**Comment by mglaman** [comment]
We can close this! The MR was merged by changing the SQLite column schema to `text`. SQLite allows performing JSON functions on `text` fields. So no patch needed :)
