### ISSUE TITLE
Please add automated tests and nightly build

### ISSUE THREAD

**Issue by rfay** [TravisCarden/ddev-drupal-xb-dev#23]
Thanks so much for exploring this territory. Could you please add (at least modest) automated tests that get run nightly?

Thanks!

Starter ideas in https://github.com/ddev/ddev-addon-template as you know.

**Comment by TravisCarden** [comment]
It's on my to-do list. 😛 I've been temporarily allocated elsewhere. I'll get on it as soon as I can make time.

**Comment by TravisCarden** [comment]
I've added [some nightly tests](https://github.com/TravisCarden/ddev-drupal-xb-dev/commit/ba4535777b974538eaa11fda9f002f598a6b69ff) that just install the add-on and test that all the commands are actually found. I'm going to consider this issue complete for now ("at least modest" was the requirement 😉). I/we can add more robust tests as warranted and as someone can make time for it. Contributions welcome. Thanks.

**Comment by rfay** [comment]
I sure appreciate it. You'll find it pays real dividends for both you and your users (and DDEV) in the long run. This is especially excellent for DDEV because it can catch problems in HEAD that might only affect XB, so we can fix before release. Thanks!
